from typing import List, Optional, Dict, Any
from sqlalchemy.orm import Session
from sqlalchemy import select
from app.models.route import Route, RouteStop
from app.schemas.route import RouteCreate, RouteUpdate
from app.crud.base import CRUDBase
from app.core.logging_config import logger


class CRUDRoute(CRUDBase[Route, RouteCreate, RouteUpdate]):
    """CRUD operations for Route model."""
    
    def create_with_stops(
        self, 
        db: Session, 
        obj_in: RouteCreate, 
        stops_data: List[Dict[str, Any]], 
        tenant_id: int
    ) -> Route:
        """
        Create a route and its stops in a single transaction.
        
        Args:
            db: Database session
            obj_in: Route creation data
            stops_data: List of dictionaries containing stop data
            tenant_id: Tenant ID
            
        Returns:
            Created Route object with loaded stops
        """
        # Create route
        db_obj = Route(
            **obj_in.model_dump(),
            tenant_id=tenant_id
        )
        db.add(db_obj)
        db.flush()  # Flush to get the route ID
        
        # Create stops
        for stop_data in stops_data:
            stop = RouteStop(
                route_id=db_obj.id,
                **stop_data
            )
            db.add(stop)
            
        db.commit()
        db.refresh(db_obj)
        return db_obj

    def bulk_create_routes_with_stops(
        self,
        db: Session,
        routes_with_stops: List[Dict[str, Any]],
        tenant_id: int
    ) -> List[Route]:
        """
        Bulk create multiple routes with their stops.
        
        Args:
            db: Database session
            routes_with_stops: List of dicts, each containing 'route' (dict) and 'stops' (list of dicts)
            tenant_id: Tenant ID
            
        Returns:
            List of created Route objects
        """
        created_routes = []
        
        try:
            for item in routes_with_stops:
                route_data = item["route"]
                stops_data = item["stops"]
                
                # Create route
                route = Route(**route_data, tenant_id=tenant_id)
                db.add(route)
                db.flush()  # Get ID
                
                # Create stops
                for stop_data in stops_data:
                    stop = RouteStop(route_id=route.id, **stop_data)
                    db.add(stop)
                
                created_routes.append(route)
            
            db.commit()
            
            # Refresh all routes
            for route in created_routes:
                db.refresh(route)
                
            return created_routes
            
        except Exception as e:
            db.rollback()
            logger.error(f"Failed to bulk create routes: {str(e)}")
            raise

    def get_by_optimization_request_id(
        self,
        db: Session,
        optimization_request_id: int,
        tenant_id: int
    ) -> List[Route]:
        """Get all routes generated by a specific optimization request."""
        stmt = select(self.model).where(
            self.model.optimization_request_id == optimization_request_id,
            self.model.tenant_id == tenant_id
        )
        return list(db.execute(stmt).scalars().all())

    def delete_by_optimization_request_id(
        self,
        db: Session,
        optimization_request_id: int,
        tenant_id: int
    ) -> None:
        """
        Delete all routes and stops associated with an optimization request.
        
        Args:
            db: Database session
            optimization_request_id: ID of the optimization request
            tenant_id: Tenant ID for isolation
        """
        # Find all routes to get their IDs
        routes = self.get_by_optimization_request_id(
            db=db, 
            optimization_request_id=optimization_request_id, 
            tenant_id=tenant_id
        )
        
        if not routes:
            return

        route_ids = [r.id for r in routes]
        
        # Delete all stops for these routes
        # Using synchronize_session=False for efficiency as we don't need to update session objects
        db.query(RouteStop).filter(RouteStop.route_id.in_(route_ids)).delete(synchronize_session=False)
        
        # Delete the routes
        db.query(Route).filter(
            Route.id.in_(route_ids),
            Route.tenant_id == tenant_id
        ).delete(synchronize_session=False)
        
        db.commit()


route = CRUDRoute(Route)
