"""Add route_status to optimization_request

Revision ID: 261fb778f4d2
Revises: ad1b2a2993d6
Create Date: 2026-03-15 12:34:39.082761

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '261fb778f4d2'
down_revision: Union[str, None] = 'ad1b2a2993d6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Create the Enum type if it doesn't exist
    routestatus = sa.Enum('scheduled', 'in_transit', 'completed', 'failed', 'processing', name='routestatus')
    
    # Add column as nullable first
    op.add_column('optimization_request', sa.Column('route_status', routestatus, nullable=True))
    
    # Set default value for existing rows
    op.execute("UPDATE optimization_request SET route_status = 'scheduled'")
    
    # Alter column to be NOT NULL
    op.alter_column('optimization_request', 'route_status', nullable=False)
    
    op.create_index(op.f('ix_optimization_request_route_status'), 'optimization_request', ['route_status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_optimization_request_route_status'), table_name='optimization_request')
    op.drop_column('optimization_request', 'route_status')
    # ### end Alembic commands ###
