"""add vehicle name in team member model

Revision ID: 2a62b365f046
Revises: a8629e4ad8cf
Create Date: 2025-12-11 19:10:15.678324

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2a62b365f046'
down_revision: Union[str, None] = 'a8629e4ad8cf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('team_member', sa.Column('vehicle', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('team_member', 'vehicle')
    # ### end Alembic commands ###
