"""add timestamps

Revision ID: 3dcb0af3a45f
Revises: 79ad66553fd4
Create Date: 2025-11-27 19:32:00.299145

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3dcb0af3a45f'
down_revision: Union[str, None] = '79ad66553fd4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('depot', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('depot', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('job', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('job', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('route', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('route', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('route_stop', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('route_stop', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('team_member', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('team_member', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('tenant', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('tenant', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('vehicle', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('vehicle', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vehicle', 'updated_at')
    op.drop_column('vehicle', 'created_at')
    op.drop_column('tenant', 'updated_at')
    op.drop_column('tenant', 'created_at')
    op.drop_column('team_member', 'updated_at')
    op.drop_column('team_member', 'created_at')
    op.drop_column('route_stop', 'updated_at')
    op.drop_column('route_stop', 'created_at')
    op.drop_column('route', 'updated_at')
    op.drop_column('route', 'created_at')
    op.drop_column('job', 'updated_at')
    op.drop_column('job', 'created_at')
    op.drop_column('depot', 'updated_at')
    op.drop_column('depot', 'created_at')
    op.drop_column('depot', 'created_at')
    # ### end Alembic commands ###
    # ### end Alembic commands ###
