"""Add assigned_to field to Job model

Revision ID: 4b6585c28191
Revises: 4a0efe37afdb
Create Date: 2025-12-10 18:22:20.362534

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4b6585c28191'
down_revision: Union[str, None] = '4a0efe37afdb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Add assigned_to column and foreign key
    op.add_column('job', sa.Column('assigned_to', sa.Integer(), nullable=True))
    op.create_foreign_key('job_assigned_to_fkey', 'job', 'team_member', ['assigned_to'], ['id'])
    
    # Change time_window_start and time_window_end from TIMESTAMP to VARCHAR
    op.alter_column('job', 'time_window_start',
                    existing_type=sa.DateTime(),
                    type_=sa.String(),
                    existing_nullable=True)
    op.alter_column('job', 'time_window_end',
                    existing_type=sa.DateTime(),
                    type_=sa.String(),
                    existing_nullable=True)
    # ### end Alembic commands ###




def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Revert time_window columns back to TIMESTAMP
    op.alter_column('job', 'time_window_end',
                    existing_type=sa.String(),
                    type_=sa.DateTime(),
                    existing_nullable=True)
    op.alter_column('job', 'time_window_start',
                    existing_type=sa.String(),
                    type_=sa.DateTime(),
                    existing_nullable=True)
    
    # Remove assigned_to column and foreign key
    op.drop_constraint('job_assigned_to_fkey', 'job', type_='foreignkey')
    op.drop_column('job', 'assigned_to')
    # ### end Alembic commands ###

