"""initial db setup

Revision ID: 79ad66553fd4
Revises: 
Create Date: 2025-11-27 13:03:18.849269

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import geoalchemy2
# revision identifiers, used by Alembic.
revision: str = '79ad66553fd4'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE EXTENSION IF NOT EXISTS postgis")
    op.create_table('tenant',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('plan_type', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tenant_id'), 'tenant', ['id'], unique=False)
    op.create_table('depot',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('location', geoalchemy2.types.Geometry(geometry_type='POINT', from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.Column('address', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # op.create_index('idx_depot_location', 'depot', ['location'], unique=False, postgresql_using='gist')
    op.create_index(op.f('ix_depot_id'), 'depot', ['id'], unique=False)
    op.create_table('job',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('draft', 'assigned', 'completed', name='jobstatus'), nullable=True),
    sa.Column('scheduled_date', sa.Date(), nullable=True),
    sa.Column('job_type', sa.Enum('delivery', 'pickup', 'service', name='jobtype'), nullable=True),
    sa.Column('location', geoalchemy2.types.Geometry(geometry_type='POINT', from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.Column('address_formatted', sa.String(), nullable=True),
    sa.Column('time_window_start', sa.DateTime(), nullable=True),
    sa.Column('time_window_end', sa.DateTime(), nullable=True),
    sa.Column('service_duration', sa.Integer(), nullable=True),
    sa.Column('priority_level', sa.Enum('low', 'medium', 'high', name='prioritylevel'), nullable=True),
    sa.Column('first_name', sa.String(), nullable=True),
    sa.Column('last_name', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('business_name', sa.String(), nullable=True),
    sa.Column('phone_number', sa.String(), nullable=True),
    sa.Column('customer_preferences', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('additional_notes', sa.String(), nullable=True),
    sa.Column('recurrence_type', sa.Enum('one_time', 'recurring', name='recurrencetype'), nullable=True),
    sa.Column('documents', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('payment_status', sa.Enum('unpaid', 'paid', name='paymentstatus'), nullable=True),
    sa.Column('pod_notes', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # op.create_index('idx_job_location', 'job', ['location'], unique=False, postgresql_using='gist')
    op.create_index(op.f('ix_job_id'), 'job', ['id'], unique=False)
    op.create_table('vehicle',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('capacity_weight', sa.Float(), nullable=True),
    sa.Column('capacity_volume', sa.Float(), nullable=True),
    sa.Column('type', sa.Enum('car', 'small_truck', 'truck', 'scooter', 'foot', 'bike', 'mountain_bike', name='vehicletype'), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vehicle_id'), 'vehicle', ['id'], unique=False)
    op.create_table('team_member',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('vehicle_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('active', 'inactive', 'online', 'offline', name='teammemberstatus'), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('role_type', sa.Enum('admin', 'driver', 'manager', name='teammemberrole'), nullable=True),
    sa.Column('external_identifier', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('phone_number', sa.String(), nullable=True),
    sa.Column('navigation_link_format', sa.String(), nullable=True),
    sa.Column('work_start_time', sa.Time(), nullable=True),
    sa.Column('work_end_time', sa.Time(), nullable=True),
    sa.Column('allowed_overtime', sa.Boolean(), nullable=True),
    sa.Column('max_distance', sa.Float(), nullable=True),
    sa.Column('break_time_start', sa.Time(), nullable=True),
    sa.Column('break_time_end', sa.Time(), nullable=True),
    sa.Column('skills', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('fixed_cost_for_driver', sa.Float(), nullable=True),
    sa.Column('cost_per_km', sa.Float(), nullable=True),
    sa.Column('cost_per_hr', sa.Float(), nullable=True),
    sa.Column('cost_per_hr_overtime', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicle.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_team_member_id'), 'team_member', ['id'], unique=False)
    op.create_table('route',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('driver_id', sa.Integer(), nullable=True),
    sa.Column('vehicle_id', sa.Integer(), nullable=True),
    sa.Column('depot_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('scheduled_date', sa.Date(), nullable=True),
    sa.Column('total_distance_meters', sa.Float(), nullable=True),
    sa.Column('total_duration_seconds', sa.Float(), nullable=True),
    sa.Column('route_polyline', sa.Text(), nullable=True),
    sa.Column('rating', sa.Float(), nullable=True),
    sa.Column('additional_notes', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['depot_id'], ['depot.id'], ),
    sa.ForeignKeyConstraint(['driver_id'], ['team_member.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicle.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_route_id'), 'route', ['id'], unique=False)
    op.create_table('route_stop',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('route_id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=True),
    sa.Column('sequence_order', sa.Integer(), nullable=True),
    sa.Column('stop_type', sa.String(), nullable=True),
    sa.Column('planned_arrival_time', sa.DateTime(), nullable=True),
    sa.Column('planned_departure_time', sa.DateTime(), nullable=True),
    sa.Column('estimated_distance_from_prev', sa.Float(), nullable=True),
    sa.Column('actual_arrival_time', sa.DateTime(), nullable=True),
    sa.Column('actual_departure_time', sa.DateTime(), nullable=True),
    sa.Column('geofence_entered_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['job_id'], ['job.id'], ),
    sa.ForeignKeyConstraint(['route_id'], ['route.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_route_stop_id'), 'route_stop', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_route_stop_id'), table_name='route_stop')
    op.drop_table('route_stop')
    op.drop_index(op.f('ix_route_id'), table_name='route')
    op.drop_table('route')
    op.drop_index(op.f('ix_team_member_id'), table_name='team_member')
    op.drop_table('team_member')
    op.drop_index(op.f('ix_vehicle_id'), table_name='vehicle')
    op.drop_table('vehicle')
    op.drop_index(op.f('ix_job_id'), table_name='job')
    op.drop_index('idx_job_location', table_name='job', postgresql_using='gist')
    op.drop_table('job')
    op.drop_index(op.f('ix_depot_id'), table_name='depot')
    op.drop_index('idx_depot_location', table_name='depot', postgresql_using='gist')
    op.drop_table('depot')
    op.drop_index(op.f('ix_tenant_id'), table_name='tenant')
    op.drop_table('tenant')
    
    # Drop custom types
    op.execute("DROP TYPE IF EXISTS jobstatus")
    op.execute("DROP TYPE IF EXISTS jobtype")
    op.execute("DROP TYPE IF EXISTS prioritylevel")
    op.execute("DROP TYPE IF EXISTS recurrencetype")
    op.execute("DROP TYPE IF EXISTS paymentstatus")
    op.execute("DROP TYPE IF EXISTS vehicletype")
    op.execute("DROP TYPE IF EXISTS teammemberstatus")
    op.execute("DROP TYPE IF EXISTS teammemberrole")
    # ### end Alembic commands ###
