"""add_route_savings_metrics_and_job_route_link

Revision ID: 7e3f4a10b828
Revises: 2a62b365f046
Create Date: 2025-12-17 17:20:07.462551

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7e3f4a10b828'
down_revision: Union[str, None] = '2a62b365f046'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('job', sa.Column('route_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'job', 'route', ['route_id'], ['id'])
    op.add_column('route', sa.Column('total_distance_saved_meters', sa.Float(), nullable=True))
    op.add_column('route', sa.Column('total_time_saved_seconds', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'job', type_='foreignkey')
    op.drop_column('route', 'total_time_saved_seconds')
    op.drop_column('route', 'total_distance_saved_meters')
    op.drop_constraint(None, 'job', type_='foreignkey')
    op.drop_column('job', 'route_id')
    # ### end Alembic commands ###
