"""Add optimization_request_id to route table

Revision ID: 892a6a122040
Revises: 8e8f59c5318b
Create Date: 2025-11-30 17:22:13.485823

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '892a6a122040'
down_revision: Union[str, None] = '8e8f59c5318b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('route', sa.Column('optimization_request_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'route', 'optimization_request', ['optimization_request_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'route', type_='foreignkey')
    op.drop_column('route', 'optimization_request_id')
    # ### end Alembic commands ###
