"""create_optimization_request_table

Revision ID: 8e8f59c5318b
Revises: d5d41496603b
Create Date: 2025-11-29 21:33:43.779709

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8e8f59c5318b'
down_revision: Union[str, None] = 'd5d41496603b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Create optimization_request table
    op.create_table(
        'optimization_request',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('tenant_id', sa.Integer(), nullable=False),
        sa.Column('depot_id', sa.Integer(), nullable=False),
        sa.Column('job_ids', sa.ARRAY(sa.Integer()), nullable=False),
        sa.Column('team_member_ids', sa.ARRAY(sa.Integer()), nullable=False),
        sa.Column('scheduled_date', sa.Date(), nullable=False),
        sa.Column('optimization_goal', sa.Enum('MINIMUM_TIME', 'MINIMUM_DISTANCE', name='optimizationgoal'), nullable=False),
        sa.Column('status', sa.Enum('QUEUED', 'PROCESSING', 'COMPLETED', 'FAILED', name='optimizationstatus'), nullable=False),
        sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('error_message', sa.Text(), nullable=True),
        sa.Column('result', sa.dialects.postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.ForeignKeyConstraint(['depot_id'], ['depot.id'], ),
        sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_optimization_request_id'), 'optimization_request', ['id'], unique=False)
    op.create_index(op.f('ix_optimization_request_tenant_id'), 'optimization_request', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_optimization_request_status'), 'optimization_request', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Drop optimization_request table
    op.drop_index(op.f('ix_optimization_request_status'), table_name='optimization_request')
    op.drop_index(op.f('ix_optimization_request_tenant_id'), table_name='optimization_request')
    op.drop_index(op.f('ix_optimization_request_id'), table_name='optimization_request')
    op.drop_table('optimization_request')
    # ### end Alembic commands ###
