"""add_job_id_to_optimization_request

Revision ID: 9e69c61d4d01
Revises: 7e3f4a10b828
Create Date: 2025-12-18 14:39:41.248324

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9e69c61d4d01'
down_revision: Union[str, None] = '7e3f4a10b828'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('optimization_request', sa.Column('job_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('optimization_request', 'job_id')
    # ### end Alembic commands ###
